
### Call `IERC20(to).balanceOf(token)`
# @prompt to To address
POST {{rpc-url}} HTTP/1.1

{ "method": "eth_call", "id": 7, "jsonrpc": "2.0", "params": [
    {
        "to": "{{to}}",
        "data": "0x70a082310000000000000000000000004d1c823b5f15be83fdf5adaf137c2a9e0e78fe15"
    },
    "latest"
] }

###
# @prompt address
POST {{rpc-url}} HTTP/1.1

{ "method": "eth_call", "id": 7, "jsonrpc": "2.0", "params": [
    {
        "to": "{{address}}",
        "data": "0x"
    },
    "latest"
] }

###
# @prompt address
# @prompt data
POST {{rpc-url}} HTTP/1.1

{ "method": "eth_call", "id": 7, "jsonrpc": "2.0", "params": [
    {
        "to": "{{address}}",
        "data": "{{data}}"
    },
    "latest"
] }

###
# isAssociated
POST {{rpc-url}} HTTP/1.1

{ "method": "eth_call", "id": 7, "jsonrpc": "2.0", "params": [
    {
        "from": "0x7D2402af7Dd0285452601489e7Ea181296f8a422",
        "to": "0x000000000000000000000000000000000038b3db",
        "data": "0x4d8fdd6d"
    },
    "latest"
] }
