
###
# HTS 0x0000000000000000000000000000000000000167
# @prompt address
POST {{rpc-url}} HTTP/1.1

{ "method": "eth_getCode", "id": 7, "jsonrpc": "2.0", "params": [ "{{address}}", "latest" ] }

###
# @prompt address
# @prompt blockNumber
POST {{rpc-url}} HTTP/1.1

{ "method": "eth_getCode", "id": 7, "jsonrpc": "2.0", "params": [ "{{address}}", "{{blockNumber}}" ] }

### `eth_getCode` using `null` address to compare behaviour
POST {{rpc-url}} HTTP/1.1

{ "method": "eth_getCode", "id": 7, "jsonrpc": "2.0", "params": [ null, "latest" ] }
