
###
# @prompt blockNumber Ethereum Block Number
POST {{rpc-url}} HTTP/1.1

{ "method": "debug_traceBlockByNumber", "id": 2, "jsonrpc": "2.0", "params": [
    "{{blockNumber}}",
    {"tracer": "callTracer"}
] }

###
POST {{rpc-url}} HTTP/1.1

{ "method": "debug_traceBlockByNumber", "id": 2, "jsonrpc": "2.0", "params": [
    "0x1796f17",
    {"tracer": "prestateTracer"}
] }

