# https://ethereum.github.io/execution-apis/docs/reference/eth_getstorageat
# https://www.alchemy.com/docs/node/ethereum/ethereum-api-endpoints/eth-get-storage-at
# https://www.quicknode.com/docs/ethereum/eth_getStorageAt
# https://docs.metamask.io/services/reference/ethereum/json-rpc-methods/eth_getstorageat/

###
# USDC on mainnet 0x000000000000000000000000000000000006f89a 0.0.456858
# USDC on testnet 0x0000000000000000000000000000000000068cDa 0.0.429274
# @prompt address Contract Address
POST {{rpc-url}} HTTP/1.1

{ "method": "eth_getStorageAt", "id": 7, "jsonrpc": "2.0", "params": [
    "{{address}}",
    "0xe",
    "latest"
] }

### missing value for required argument 2
POST {{rpc-url}}{{$processEnv %apiKey}} HTTP/1.1

{ "method": "eth_getStorageAt", "id": 7, "jsonrpc": "2.0", "params": [
    "0x000000000000000000000000000000000006f89a",
    "0xe"
] }

###
# USDC
POST {{rpc-url}}{{$processEnv %apiKey}} HTTP/1.1

{ "method": "eth_getStorageAt", "id": 7, "jsonrpc": "2.0", "params": [
    "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
    "0x1",
    "latest"
] }

### missing value for required argument 2
# USDC
POST {{rpc-url}}{{$processEnv %apiKey}} HTTP/1.1

{ "method": "eth_getStorageAt", "id": 7, "jsonrpc": "2.0", "params": [
    "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
    "0x1"
] }

###
# @prompt block Block Number
POST {{rpc-url}}{{$processEnv %apiKey}} HTTP/1.1

{ "method": "eth_getStorageAt", "id": 7, "jsonrpc": "2.0", "params": [
    "0x000000000000000000000000000000000006f89a",
    "0xe",
    "{{block}}"
] }
